CREATE TABLE IF NOT EXISTS pax.games (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    gameName VARCHAR NOT NULL,
    created TIMESTAMP DEFAULT NOW(),
    lastModified TIMESTAMP DEFAULT NOW(),
    inhabited BOOLEAN DEFAULT 'TRUE'
);
