CREATE TABLE IF NOT EXISTS pax.players (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    playerName VARCHAR NOT NULL,
    created TIMESTAMP DEFAULT NOW(),
    lastModified TIMESTAMP DEFAULT NOW()
);
