CREATE TABLE IF NOT EXISTS pax.planets (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    planetName VARCHAR NOT NULL,
    systemId INT REFERENCES pax.systems(id) ON DELETE SET NULL,
    created TIMESTAMP DEFAULT NOW()
);
